spring:
  application:
    name: tracking-app

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "prometheus", "metrics"]
    endpoint:
      health:
        show-details: true
      metrics:
        enabled: true
      prometheus:
        enabled: true

server:
  port: 8080
jwt:
  secret: 123456